### ISSUE TITLE
[Lessons Page] - Filters

### ISSUE THREAD

**Issue by sdpeyton** [GeoSurge/teachosm#11]
## Description
On the lessons page, the user should be able to press a "filters" button on the top right-hand side of the screen which opens up a filter menu for more advanced search. 

## Acceptance Criteria
- [ ] Create a filter button to open up the menu
- [ ] Create a side-bar menu which opens up over the rest of the page

Add these filters;
- [ ] Audience [add specific levels here]
- [ ] Difficulty level [add specific levels here]
- [ ] Preparation time [add specific levels here]
- [ ] Duration [add specific levels here]

## Mocks

![image](https://user-images.githubusercontent.com/11160004/54169432-13fa8f80-4449-11e9-8898-b366474f3e4c.png)

![image](https://user-images.githubusercontent.com/11160004/54169443-1bba3400-4449-11e9-9865-b3d74010b84f.png)

**Comment by mcawley** [comment]
Looking great. What feedback is required here? Language for each category?

**Comment by geomantic** [comment]
Yes please, add language as a tag/category. We'd like to solicit content in languages other than English.

**Comment by shawnmgoulet** [comment]
These would match up with the categories & tags in #19, yeah?

**Comment by d3netxer** [comment]
yes they will match up with the categories & tags in #19 . So we can add language to the that list. I suggest for UI purposes, maybe having the English category pre-selected as default.

**Comment by shawnmgoulet** [comment]
Makes sense to me that english would be default.

**Comment by geomantic** [comment]
@shawnmgoulet @mcawley just wondering: does it make sense to have a filter here for 'Setting' - 'Armchair Mapping','Field Mapping' ??

**Comment by shawnmgoulet** [comment]
yes, it makes sense to add that Steven.

**Comment by mcawley** [comment]
Teachers might be confused by the armchair term. Desktop mapping? mobile mapping?

**Comment by shawnmgoulet** [comment]
yeah, that might be true - even classroom mapping could work (in the educational setting case). We have to pick something and go with it...

**Comment by d3netxer** [comment]
other terms are 'remote mapping' and 'field mapping'. Also some projects may not even be about mapping, but be more about analysis using open map data. Maybe these terms can be represented with the tags?

**Comment by shawnmgoulet** [comment]
See Add Lesson Page - Filters and Tags and let's go with the 3 listed there 1st by @mcawley.

**Comment by sdpeyton** [comment]
Apologies for the late response, that sounds good, lets go with the 3 listed in the other ticket

**Comment by sdpeyton** [comment]
done
