### ISSUE TITLE
Adding a new project

### ISSUE THREAD

**Issue by geomantic** [GeoSurge/teachosm#110]
I uploaded some fresh content to the shiny new TeachOSM site but it's gone into the ether. 

Remind me who gets the notification that new content has been posted? Presumably, we'd be reviewing and approving submittals.

**Comment by d3netxer** [comment]
Ok awesome, I see it in this pull request: https://github.com/GeoSurge/teachosm/pull/109 

Do you want to try merging in the pull request @geomantic ? 

It will pull it into this repo, and not the live OSMUS repo. But then I can manually add it to the OSMUS repo if you want.

About the notifications. There should be a way to receive e-mail notifications of new pull requests, can you try 'watching' this repo?

**Comment by geomantic** [comment]
@d3netxer Thanks, Tom. OK, I merged the PR and will check it out...

Also, I'm already watching this repo, but changed my level so now I'm notified anytime anyone does ANYthing.
