### ISSUE TITLE
[Lessons] - Tags

### ISSUE THREAD

**Issue by sdpeyton** [GeoSurge/teachosm#12]
## Description
In addition to the free-form search and filters, users should also be able to select tags that they would like to narrow their search down from. When users add tags, these should be treated as an **INCLUSIVE** search, meaning that any lessons that have one or more of the selected tags should show up. If possible, we should order them by the number of matching tags.

## Acceptance Criteria
- [ ] Add the ability in the "filters" menu to select tags
- [ ] As tags are selected, they should update the lessons queue

## Mocks

![image](https://user-images.githubusercontent.com/11160004/54169550-7eabcb00-4449-11e9-9d40-f987bc1c09fa.png)

**Comment by d3netxer** [comment]
let's try to add in a way to group projects together in the data model, but maybe not include the option in the UI at this point. Let's discuss.

**Comment by sdpeyton** [comment]
Done
