### ISSUE TITLE
[Blog Page] - Individual blog post

### ISSUE THREAD

**Issue by sdpeyton** [GeoSurge/teachosm#16]
## Description
When a user clicks on a blog on the blogs page, it needs to link out to the full blog post.

## Acceptance Criteria
- [x] Build a way of translating blog posts into individual pages
- [x] Link back to the main blog

## Mocks

We don't have mocks for this but it should be fairly straightforward. Some kind of out-of-the-box jekyll markdown template conversion stuff should suffice.

**Comment by d3netxer** [comment]
ok this should be complete
