### ISSUE TITLE
[Sign In Page] - Authentication

### ISSUE THREAD

**Issue by sdpeyton** [GeoSurge/teachosm#17]
## Description
In order to be able to differentiate between different contributors (to determine who is allowed to edit what and present information on who uploaded what), we need some way of authenticating users.

The method we decided on was to go with OSM's o-auth system. Users would sign in to their OSM account and we would use those credentials to verify users.

For more information, talk to @DanielJDufour 

## Acceptance Criteria
- [ ] Create a "Sign in" page that has inputs for a username and password
- [ ] When the user submits their credentials, verify the u/p against OSM's api
- [ ] When a valid credential is received, store this somehow (localstorage?) so that it can be used across the site.

## Mocks

![image](https://user-images.githubusercontent.com/11160004/54170431-18c14280-444d-11e9-9246-180666d8841a.png)

**Comment by DanielJDufour** [comment]
AFAIK, OSM's OAuth account registration doesn't permit sending user names and passwords via an AJAX request.  You actually have to visit openstreetmap.org's oauth page, which then redirects you to TeachOSM with an access_token.  In other words, we have to use OSM's login page and not create our own.  Happy to be corrected wrong :-)

**Comment by DanielJDufour** [comment]
User Credentials Policy: https://wiki.openstreetmap.org/wiki/User_Credentials_Policy

**Comment by DanielJDufour** [comment]
Authentication Flow

**Logging in**
1. User clicks login on teachosm.org
2. User logs in on openstreetmap.org
3. User kicked back to teachosm.org with access token
4. TeachOSM saves the access_token as a cookie


**Submitting a Change**
1. User submits a change with access token
2. AWS Lambda Function verifies that user id matches to access token (/api/0.6/user/details)
3. Lambda function logs into Github under a Machine Account and submits a Pull Request to TeachOSM repository

**Comment by d3netxer** [comment]
- We are going with the option where projects will be submitted without any authorization. There will be a captcha that will prevent bots/spam from submitting projects. The user will also have a field available where they will be able to input their OSM username.

**Comment by d3netxer** [comment]
we also discussed adding a statement to the project upload form that states that all material uploaded to the form needs to be at the most restrictive a CC BY license or less.
