### ISSUE TITLE
[Add Lesson Page] - Add materials + material info

### ISSUE THREAD

**Issue by sdpeyton** [GeoSurge/teachosm#18]
## Description
We need a way for users to be able to submit course materials. This can be done through a simple form where they input basic information about the lesson, like the title, description, and the actual course material.

## Acceptance Criteria
Add ability to input:
- [ ] Title
- [ ] Description
- [ ] Course material [add acceptable formats here]

Additionally:
- [ ] Show their osm id and name
- [ ] If their osm account doesn't have a name, prompt them to add it

## Mocks

![image](https://user-images.githubusercontent.com/11160004/54170721-1f9c8500-444e-11e9-8cac-0cd514ff6b65.png)

**Comment by shawnmgoulet** [comment]
This looks good to me. Is this where we need a space for the contributor to add their contact information (e.g. email, OSM username, etc.) or is that happening somewhere else?

**Comment by geomantic** [comment]
Probably need a link back to privacy policy in here?

**Comment by shawnmgoulet** [comment]
What do you need here @sdpeyton ?

**Comment by geomantic** [comment]
On second thought, probably *NOT* a need for a link back to privacy policy.

**Comment by shawnmgoulet** [comment]
Let's make sure we change "lesson" everywhere to "project".

**Comment by sdpeyton** [comment]
Done
