### ISSUE TITLE
[Add Lesson Page] - Filters and Tags

### ISSUE THREAD

**Issue by sdpeyton** [GeoSurge/teachosm#19]
## Description
When adding a lesson, users need to be able to set their filters and tags so that their lessons can easily be found.

## Acceptance Criteria
- [ ] Add all filters [specify which filters and what options are available here]
- [ ] Add ability to add tags (punting on creating new tags for now)

## Mocks

![image](https://user-images.githubusercontent.com/11160004/54170778-583c5e80-444e-11e9-95df-9e98cb12cccc.png)

**Comment by d3netxer** [comment]
for tagging implementation, look into the following: 
- https://github.com/algolia/autocomplete.js/
- https://github.com/yairEO/tagify

**Comment by geomantic** [comment]
These sorts of all inclusive lists are always as challenge: a new category is discovered just as the list is finalized. Suggest a means for adding another user-defined classification option.

**Comment by shawnmgoulet** [comment]
While I agree keeping things open-ended could be useful, I do think TOSM has to be rigid here and establish boundaries.

My suggestions:

**1. Audience**
- High School / Secondary
- Community College

**2. Difficulty**
- Beginner
- Advanced

**3. Educator Preparation Time**
- Hours
- Days
- Weeks

**4. Education Activity Duration**
- 1 hour
- 2-4 hours
- 1 Day
- Week
- Week +

**Pre-canned Tags**
_1st 6 = sections of the AP Human Geography high school course_
- Population & Migration
- Cultural Patterns & Processes
- Political Organization of Space
- Agriculture, Food Production & Rural Land Use
- Industrialization and Economic Development
- Cities and Urban Land Use
- GIS
- Environmental
- Mapping

**Comment by d3netxer** [comment]
I like these tags. 1 minor suggestion, for 

- 1 Day
- Week

for consistency have the '1' show for both labels or neither

**Comment by shawnmgoulet** [comment]
I agree Tom.

**Comment by mcawley** [comment]
Let's keep talking through this - thanks for the initial ideas Shawn!

**Comment by d3netxer** [comment]
We discussed at tonight's meeting:
- different ways duration can be split into different categories
- adding a radio button the user uploading a post can switch on if they are adding a video, if so an extra field can appear where they will be able to add the youtube video link
- adding a tag that a user can specify if the project is a 'remote mapping' project or 'field mapping' project. (terms can be up for discussion as well)

**Comment by mcawley** [comment]
I simplified the AP tags added many tags... Here's my list for discussion:

**1. Audience**

- Primary
- High School / Secondary
- Community College
- University
- Other - (something for non institutionalized learners …) 

**2. Difficulty**

- Beginner
- Intermediate
- Advanced

**3. Educator Preparation Time**

- < 1 hour
- Hours
- Days
- Weeks

**4. Education Activity Duration**

- < 1 hour
- 1 hour
- 2-4 hours
- 1 Day
- Multiple days
- Week
- Week +

**Pre-canned Tags**

- Data
- Validation
- Field
- Roads
- Buildings
- Points of Interest
- Local
- Regional
- National
- History
- Science
- Social Studies
- Sports
- Art
- Education
- Music
- Mathematics
- Statistics
- International
- Industrialization
- GIS
- Environment
- Mapping
- Geography
- Politics
- Economic
- Culture
- Population
- Migration
- Cities
- Land Use 
- Agriculture

**Comment by mcawley** [comment]
We should finalize the categories and the titles for the project type either 'Remote Mapping Project' & 'Field Mapping Project' (which I'm fine using both) or something else.

Thinking: 
Project Type = 
- Desktop
- Field / Outdoor
- Mobile

**Comment by shawnmgoulet** [comment]
Sounds good to me @mcawley. I'm good with those 2 titles and project types. Thinking it might provide clarity & beneficial to provide examples for each.

e.g.

- Desktop | TeachOSM Tasking Manager, HOTOSM Tasking Manger contributions, etc.

- Field / Outdoor | The use of mobile applications, Field Papers, Pen and Paper mapping outdoors and on site

- Mobile | The use of mobile applications to contribute to mapping projects such as StreetComplete, MAPS.ME, MapSwipe, etc.

Is that what you were thinking?

**Comment by DanielJDufour** [comment]
Good feedback from an educator today.  Here is a paraphrasing:
```
1) Educators would probably stay away from anything that would take weeks of preparation
2) Educator said that she mostly thinks in hours.  What a "week" is can be ambiguous.
3) Difficulty filter is helpful
4) Educator would want to know the ideal workflow for doing a certain type of analysis
5) There may be a need for describing the sequence of projects or what the pre-requisites are
```

@mcawley suggested that it might be a good idea to have a Case Studies section.

**Comment by geomantic** [comment]
That's useful info, @DanielJDufour though I'm guessing that the 'analysis' referred to in 4) is more akin to, 'how do I apply this stuff'.  If not, maybe you can clarify.

Also, are we not porting over the existing case studies we have on the website? At any rate, yes, we should have a Case Studies section.

**Comment by shawnmgoulet** [comment]
I'm good with stripping off anything to do with week and going with what @mcawley proposed. @geomantic - could you confirm or update so we could finalize this before the meeting this week?

**Comment by DanielJDufour** [comment]
@geomantic , I think you're probably correct on what the teacher was trying to communicate with (4), but I'm far from sure.  @mcawley might have understood better than me.

**Comment by geomantic** [comment]
@shawnmgoulet confirming. Do away with week entirely, but perhaps add a category for "1 day+" ??

**Comment by geomantic** [comment]
@shawnmgoulet @DanielJDufour Also, any pre-requisites should be listed on the project, rather than as a filter setting IMHO.

**Comment by shawnmgoulet** [comment]
Let's go with 1 day & multi-day for the "days" project duration categories.

How about we go ahead and have the project uploader add prerequisites and for this section, we have an ID button that offers some guidance giving an example such as: for this project, you should have made changesets, added hashtags and used overpass-turbo.

**Comment by sdpeyton** [comment]
I'm not sure I understand the "type" concept - is that supposed to be another filter in addition to audience, difficulty, preparation time and activity duration?

**Comment by shawnmgoulet** [comment]
Yes, that's the type of project it is and corresponds to where & how the educator would implement the project. That would be another filter of the project.

**Comment by geomantic** [comment]
@shawnmgoulet @sdpeyton I can see how 'Type' could be ambiguous. Maybe 'Setting' is what we're after?

**Comment by d3netxer** [comment]
as discussed in tonights meeting. We will start with a more 'constrained tag list', including these tags:
- Population & Migration
- Cultural Patterns & Processes
- Political Organization of Space
- Agriculture, Food Production & Rural Land Use
- Industrialization and Economic Development
- Cities and Urban Land Use
- GIS
- Environmental

**Comment by d3netxer** [comment]
as discussed in tonight's meeting, we will include adding a group or sequence of projects in the data model.

**Comment by mcawley** [comment]
What is the benefit of having fewer tags?

**Comment by mcawley** [comment]
These are very specific, and could potentially constrain the user. I have some existing material that will not fit in any of these categories - it's just the basics of OSM.

**Comment by mcawley** [comment]
Ideal workflow above from educator meant - if I take this module what should be next? How do we tag if there is a full course of material to upload that could be used through an entire semester or school year?

**Comment by d3netxer** [comment]
The benefit of having fewer tags would be cluttering the UI less. However, maybe there are other options we can take: 
1. If we have an expanded tag list, maybe we don’t have to display all of them on the user upload form, but instead just allow them to be used in auto-complete 
2. I suggest for the project cards that only the first x tags be displayed to prevent cluttering. All of the tags can be displayed on the separate project page
3. I want to note that we are still planning on having the functionality for users to add their own tags

**Comment by mcawley** [comment]
Like the suggestions thanks! Didn't realize #3 - great.

**Comment by shawnmgoulet** [comment]
I think of the tags as being a list of options to select, so the number of options, would be the same amount of work (for GS to build in data model) for 50 as apposed to having say 10, right?

_If that's the case_, then I think we can keep _as many tags as necessary_, but some of these are unnecessary. For instance, "mapping" and "geography", obviously all of these projects are related to both, so they don't seem too useful to me. I think we skim off the ones that don't add specific context to the project and keep only those that add that level of context.

In regards to showing the tags, could we maybe limit any 3 (or some small number) to the tiled page and then show all in the project-specific page?

In regards to showing all the tags on the upload form, maybe we could use auto-complete rather than showing all for a radial-style selection for the uploader?

**Comment by mcawley** [comment]
Agree with top 3 being added to the tiled page. When I added mapping and geography I thought it might help us remove any that are not relevant to be on our site, and also that any geography teachers using the site might search for it as a tag.

**Comment by sdpeyton** [comment]
Done
