### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by sdpeyton** [GeoSurge/teachosm#2]
## Description
Create a navigation bar that is present on all pages across the site. 

Links: 
- [x] Landing page (TeachOSM logo)
- [ ] Blog
- [x] Lessons
- [ ] Sign in (This should be a distinct button so it can pop out amidst the others)

Navigation bar should be black with a green hover for links across all pages except the hero section of the home page where it is transparent.

## Mocks
![image](https://user-images.githubusercontent.com/11160004/54167714-764f9200-4441-11e9-956f-72a53e4c242c.png)

## Reference Links
Whimsical mocks: https://whimsical.co/UEWkzkEhUxqWcZ6QqJbKVY

## Acceptance Criteria
1. Navigation bar with links is created and made to be easily incorporated into any template across any page.

**Comment by geomantic** [comment]
Suggest we substitute the word, 'Project' for 'Lessons'

**Comment by d3netxer** [comment]
complete
