### ISSUE TITLE
[Add Lesson Page] - Lambda to handle submits

### ISSUE THREAD

**Issue by sdpeyton** [GeoSurge/teachosm#21]
## Description
When a user submits a lesson, we need a way of handling the submission such that TeachOSM can be notified of the new submission and have an opportunity to review it prior to accepting or declining the submission.

@d3netxer can you add more to this ticket to explain how this process will work?

## Acceptance Criteria
- [ ] It works

**Comment by d3netxer** [comment]
did a very preliminary test of https://github.com/vladgolubev/serverless-libreoffice conversion to pdf function and it worked

**Comment by d3netxer** [comment]
This is a preliminary plan of the Lambda function:

# teachosm-serverless-lambda

This Lambda function processes project submissions via TeachOSM website.

## TeachOSM site

user upload form content:

-google captcha
-fields
-tags
-thumbnail
-youtube link
-content

## Steps:

1. User submits form

2. Lambda processes Google Captcha

3. If Google Captcha sucessful, TeachOSM Lambda continues processing form data:

-creates a metadata form

-if content, then:
  -save content to S3 (prepend with datetime)
  -convert content to word doc and pdf
  -save links in metadata form

if thumbnail:
  -prepend filename with datetime
  -save link in doc metadata form

Lambda makes a github pull request with the metadata form (markdown with yaml front-matter)

4. On TeachOSM site after successful submission, a completed message is sent to the user.

**Comment by d3netxer** [comment]
I started developing a new repo on my username. We can fork it to the GeoSurge repo in time.

**Comment by d3netxer** [comment]
flagging @sdpeyton . We need to add a youtube link to the metadata; and also make it an option to include a youtube link during form submission
