### ISSUE TITLE
[Landing Page] add calendar of events

### ISSUE THREAD

**Issue by d3netxer** [GeoSurge/teachosm#23]
## Description
Inserting a calendar on the landing page using fullcalendar.js from https://fullcalendar.io. 

This calendar will integrate with a TeachOSM Google Calendar.

**Comment by d3netxer** [comment]
@shawnmgoulet I am going to need a googleCalendarApiKey and googleCalendarId from the TeachOSM Google Calendar to finish the integration. You can follow these directions: https://fullcalendar.io/docs/google-calendar 

Or you can give me full permissions to the calendar and I can do it.

**Comment by shawnmgoulet** [comment]
@geomantic @mcawley - is there a TeachOSM Google Calendar set up or do I need to do that?

**Comment by geomantic** [comment]
Yes, we have one, but it was created under my acct, so I should probably create a new one as part of OSMUS team drive. 

--SEJ

**Comment by shawnmgoulet** [comment]
Yes, we need to set one up that is specifically for TeachOSM-related events. [This may help](https://support.google.com/a/answer/1626902?hl=en).

**Comment by geomantic** [comment]
@shawnmgoulet We now have a calendar. Here's a link to add it to your calendar:
openstreetmap.us_ohbvfo9oui0534gj2t9ijfe1co@group.calendar.google.com

**Comment by d3netxer** [comment]
ok great, can I have the googleCalendarApiKey as well @geomantic ?

**Comment by d3netxer** [comment]
ok, this is completed : )

**Comment by d3netxer** [comment]
fix the x button to close the event pop-up

**Comment by d3netxer** [comment]
Okay, fixed the close icon : )
