### ISSUE TITLE
Assets not loading when developing on server

### ISSUE THREAD

**Issue by DanielJDufour** [GeoSurge/teachosm#25]
## Description
Assets like CSS and images aren't appearing when I'm developing on my EC2 instance and use --host =0.0.0.0

## Acceptance Criteria
CSS and images load

## Reference Links

![image](https://user-images.githubusercontent.com/4313463/54252358-dc5f1680-4520-11e9-9b64-7fd1bea0d762.png)

I think the solution will be to remove siteurl when it is unnecessary.  We should be able to point to the root of the site with urls that starts with `/`.

**Comment by d3netxer** [comment]
good point. Try replacing instances of '{{site.url}}' with '{{site.baseurl}}' and see if that take care of it.

**Comment by DanielJDufour** [comment]
@d3netxer , good point. I'll try that!

**Comment by d3netxer** [comment]
ok fixed.
