### ISSUE TITLE
OAuth Legalese Questions

### ISSUE THREAD

**Issue by DanielJDufour** [GeoSurge/teachosm#26]
## Description
Can we use OAuth to verify users?

From https://wiki.openstreetmap.org/wiki/API#Terms_of_use:
```
The editing API is provided in order to edit the map data, not for read-only purposes or projects. 
```

## Reference Links
https://wiki.openstreetmap.org/wiki/API#Terms_of_use

**Comment by geomantic** [comment]
@DanielJDufour Shawn and I talked w/ Mikel today about this issue. We'll have to find a different method. The consensus is that using OAuth for something one step removed from editing is bound to cause friction. @shawnmgoulet can add more.

**Comment by DanielJDufour** [comment]
Roger that.  I'll start working up alternatives.

**Comment by DanielJDufour** [comment]
Here are some alternatives.  I'll start experimenting with them this week:
1) Original Proposal: People can submit a new lesson without authenticating and people can submit changes to any lesson without authenticating.  A TeachOSM member with a Github account will QA every pull request.
2) Authenticate with Github OAuth.  This would require people to sign into Github before submitting a new lesson.  We could also restrict editing to only your lessons.
3) Google OAuth. This would allow us to verify the author of a lesson by their email address.  However, it would require all contributors to have a google account.  How reasonable is this?  I'm assuming google accounts are more common place than Github accounts, but it's an assumption.
4) Setting up a common identity service that other geospatial apps could use.  This is probably outside the scope of this project though.

I'll keep you updated on my progress.

**Comment by shawnmgoulet** [comment]
Thanks Daniel. Seems like we ask them to submit their contact info if they wish to share and call it a day.

**Comment by shawnmgoulet** [comment]
@geomantic & @mcawley anything to add?

**Comment by mcawley** [comment]
how do other things work like the Pascal Neis tools then? You have to log into OSM for those...

**Comment by geomantic** [comment]
Would we open ourselves up to endless reams of spam if we allowed anyone to contribute? I'd like to make it as painless as possible. Maybe we have them enter stuff in a 3- or 4-part form with a captcha or something?

**Comment by DanielJDufour** [comment]
@mcawley , great question.  Are you referring to http://resultmaps.neis-one.org/oooc?  I believe that app is not currently requiring a login (or maybe that feature was removed?).  He appears to be avoiding using the API by downloading weekly changesets, processing it, and then serving up the data through his own API. (http://neis-one.org/2013/01/oooc/)
 
Meet Your Mappers (https://mym.rtijn.org/) which we've discussed before also appears to avoid asking for a user login.  I'm not sure internally how that works.

The OSM Wiki does require a login, but it appears to be a different authentication system and doesn't connect to the openstreetmap.org API.  I tried to use my OSM account to log into the Wiki and it didn't work.

**Comment by DanielJDufour** [comment]
@geomantic , good point.  We'll make sure to weed out the spam.  Captcha is a great idea and we'll also make sure to add some data validation to the AWS Lambda job that processes the form submission, so spam submissions never make it to you :-)

**Comment by DanielJDufour** [comment]
I was wondering what you all think about option 3 (using Google's OAuth).  I researched the Google documentation and it looks like it would be fairly painless to verify that a user's email address is correct.

**Comment by geomantic** [comment]
@DanielJDufour Does it lock us into Google's stack? Philosophically I'd lean to an open source solution, but don't want to be dogmatic if this is a pragmatic solution. Certainly there would be costs associate with switching later on, but I can't estimate what they'd be. @shawnmgoulet likely has a better understanding than I do.

**Comment by shawnmgoulet** [comment]
so they'll need to have a Google acct or no? They'd login like [this](https://developers.google.com/identity/sign-in/web/sign-in#add_a_google_sign-in_button) or something else?

**Comment by DanielJDufour** [comment]
Good questions.  Using Google wouldn't necessarily exclude other methods of verification.  We could also integrate with other email providers if they have OAuth functionality.  I was mainly suggesting Google because it would be a way to verify that a user trying to edit a lesson created by email somerandomemail@gmail.com actually has access to the email somerandomemail@gmail.com.

That being said, if we want to assume that impersonation isn't a big problem (and that's probably a good assumption), then option number 1 would work.

My personal opinion is that we should go with number one because it requires the least amount of maintenance.  I know we won't want to update the login process when Google updates their API on every several months.  I just wanted to make sure I presented option 3 as a technical solution to verification of Google email accounts.  I'm happy to do as @shawnmgoulet suggested and to just ask for user emails when they make new submissions or changes to lessons :-)

**Comment by shawnmgoulet** [comment]
So, how about option 1 + requiring to share their email address in a field?

**Comment by DanielJDufour** [comment]
Sounds good

**Comment by DanielJDufour** [comment]
Closing this.  Think I have my marching orders.  Feel free to reopen if you think it necessary :-)

**Comment by DanielJDufour** [comment]
Per the meeting tonight, we will be collecting OSM usernames instead of email addresses.
