### ISSUE TITLE
[Landing Page] - footer - Privacy Policy  and/or Terms of Use

### ISSUE THREAD

**Issue by d3netxer** [GeoSurge/teachosm#28]
## Description

are  Privacy Policy  and/or Terms of Use needed on the footer? If so, please provide text.

## Reference Links

terms and conditions example: https://www.pandadoc.com/website-standard-terms-and-conditions-template/?ev2=1

privacy policy example: https://www.bbb.org/greater-san-francisco/for-businesses/toolkits1/sample-privacy-policy/

**Comment by shawnmgoulet** [comment]
This is a question for @mcawley & @geomantic. OSM US doesn't have anything on their site, but it probably makes sense to add something here, even if using a [license](https://choosealicense.com/)?

**Comment by geomantic** [comment]
@shawnmgoulet  Yaa, I, lieu of an explicit US policy, I think it makes sense to link back to the OSMF [privacy policy](https://wiki.osmfoundation.org/wiki/Privacy_Policy) as well as the [license](https://wiki.osmfoundation.org/wiki/Licence). As a historical norm, we've always adhered pretty close to OSMF policies.

**Comment by geomantic** [comment]
@shawnmgoulet As far as the actual TeachOSM content, we should probably look around the project to look for a compatible license, CC-by-something, in all likelihood. I'm fine with a license that allows commercial use with share-alike and attribution.

**Comment by d3netxer** [comment]
- I can see how it could be beneficial for the TeachOSM site to have two documents that can be linked on the footer. 1) A privacy policy that links to the OSMF privacy policy, but also describes privacy policy of the site itself, which I imagine would be brief as we are storing very little private data if any. 2) A license page that describes the license/licenses used on the site, as well as links to the OSM license.
- without the risk of overcomplicating things. Maybe when users upload projects, there can be a choice of license to choose? (I'm thinking some users may want to upload as CC0, while others may want to use CC-by-something) As well maybe there should be a default choice.

**Comment by shawnmgoulet** [comment]
I'm 100% no expert on OS licensing and I'm pretty sure the "Ed Portal" users won't be either. Like myself, they won't know the differences between CC0 & CC-by-something. This needs to be decided by @geomantic / the OSM US Board. I don't know where to go with this.

**Comment by geomantic** [comment]
Oh I missed your point, @d3netxer Right, I think a simple statement that says what we store and for how long, how we use that info

**Comment by d3netxer** [comment]
we discussed in tonight's meeting that we can:
- provide simple language for the privacy policy that states some to the effect that the site only collect OSM usernames. It was something to this effect. @TeachOSM, please refine language.

**Comment by d3netxer** [comment]
Also for 'Terms of Use' we discussed the possibility of adding language that specifies the site and the projects follow a CC BY license or a less restrictive license (https://creativecommons.org/licenses/). Something to this effect. Please refine language @TeachOSM

**Comment by shawnmgoulet** [comment]
I believe @geomantic has the answers to these 2 questions.

**Comment by geomantic** [comment]
Just checking the HOT homepage and they have a banner at the bottom of the page with the obligatory this-site-uses-cookies-click-here-okay and links to [their privacy policy](https://www.hotosm.org/privacy). It's also on GitHub [here](https://github.com/hotosm/legal). 

I see no reason not to copy it wholesale and replace 'HOT' with 'TeachOSM' since it is appropriately licensed.

**Comment by geomantic** [comment]
@d3netxer Re: Terms of use, I think the choice is between [CC By-SA](https://creativecommons.org/licenses/by-sa/4.0/) or plain ol' [CC By](https://creativecommons.org/licenses/by/4.0/). By SA will be more restrictive, but still quite liberal.

**Comment by shawnmgoulet** [comment]
I'm fine with moving forward with re-mixing off HOT's privacy.

**Comment by shawnmgoulet** [comment]
I'm not seeing Terms of Use anywhere on HOT's site or the HOT TM - can anyone find it?

**Comment by geomantic** [comment]
@shawnmgoulet no, cannot find terms of use. But their situation is a bit different as they're not publishing materials, so maybe they don't need one?

**Comment by shawnmgoulet** [comment]
Let's go with CC By-SA. Let's tell the user up front that it's such and link to the [CC By-SA creative commons page ](https://creativecommons.org/licenses/by-sa/2.0/).

**Comment by d3netxer** [comment]
Ok, I took a first stab of making edits to the privacy policy and creating a terms of use; and I added them to the development site.

They are in markdown, so they are easy for you all to edit and make a pull request, or you can just e-mail us requested changes.

privacy policy: https://github.com/GeoSurge/teachosm/blob/master/_includes/privacy-policy.md

terms of use: https://github.com/GeoSurge/teachosm/blob/master/_includes/terms-of-use.md

For the privacy policy I tried to delete sections that are not applicable to us.

For the terms of use, I started with the terms of use from the US council of non-profits (https://www.councilofnonprofits.org/terms-of-use). I then deleted parts that I thought didn't apply to TeachOSM, and I added the CC licensing. 

For both docs, I am not sure how the language works because TeachOSM is chartered by OpenStreetMapUS. I am not sure how this should be worded, or when TeachOSM or OpenStreetMap US should be referred to.

please review @shawnmgoulet and @geomantic when you have time.

**Comment by d3netxer** [comment]
closing, Privacy Policy and Terms of Use have been edited and reviewed
