### ISSUE TITLE
Replace all instances of the word, 'lesson' with 'project'

### ISSUE THREAD

**Issue by geomantic** [GeoSurge/teachosm#29]
## Description
I risk coming across as pedantic about nomenclature but words matter. And the word 'lesson' sounds pedantic. So I'd like to suggest we scour it from the repo and replace it with the word 'project'. 
Another reason I want to use the word 'project' is because many schools are adopting the [project-based learning model](https://www.edutopia.org/project-based-learning) and to educators and students in the PBL world, the word 'lesson' comes across as dated. Moreover, the TeachOSM approach to mapping is essentially what we're trying to promote:

> Project-based learning is a dynamic classroom approach in which students actively explore real-world problems and challenges and acquire a deeper knowledge.

I suggest we do this for our internal references as well as public-facing pages to be consistent.

**Comment by d3netxer** [comment]
ok done
