### ISSUE TITLE
[Resources Page]

### ISSUE THREAD

**Issue by viymak** [GeoSurge/teachosm#32]

**Comment by geomantic** [comment]
- Placeholder on this page for a glossary
- Links to 3rd partly videos, how-to's, etc. that go into greater detail on particular subjects. 
- what else goes here?

**Comment by geomantic** [comment]
Glossary could be in markdown, so we can update as we go?

**Comment by d3netxer** [comment]
as discussed at the meeting tonight, we are thinking of adding the glossary as a separate page, but linked as one of the resource choices in the grid layout.

**Comment by shawnmgoulet** [comment]
Let's go with implementing this as proposed here please.

**Comment by sdpeyton** [comment]
Too vague of a ticket now, basically done
