### ISSUE TITLE
Adding a 'Donate to TeachOSM' button

### ISSUE THREAD

**Issue by geomantic** [GeoSurge/teachosm#33]
## Description
Add a button to the landing page to solicit donations to the TeachOSM project.
## Acceptance Criteria
Link to the [existing donation form](https://osmus.wufoo.com/forms/openstreetmap-us-donation-form/)

**Comment by d3netxer** [comment]
are we thinking of adding this in the footer or somewhere in the About section?

**Comment by shawnmgoulet** [comment]
My vote is to add it to the footer.

**Comment by shawnmgoulet** [comment]
Let's go with adding this to the footer please.

**Comment by d3netxer** [comment]
Ok, moved the Donate button to the navbar : )
