### ISSUE TITLE
[Landing Page] - About section

### ISSUE THREAD

**Issue by sdpeyton** [GeoSurge/teachosm#4]
## Description
Create an about section directly below the 

## Acceptance Criteria
- [x] Title (add title here)
- [x] Description (add description here)
- [x] Highlight 1 (add first highlight title and description here)
- [x] Highlight 2 (add second highlight title and description here)
- [x] Highlight 3 (add third highlight title and description here)

## Mocks
![image](https://user-images.githubusercontent.com/11160004/54167911-8025c500-4442-11e9-9a0a-30d990198a7b.png)

![image](https://user-images.githubusercontent.com/11160004/54167905-756b3000-4442-11e9-8671-6dce1655f492.png)

**Comment by shawnmgoulet** [comment]
**About TeachOSM**
**_(needs to be shortened)_**
TeachOSM was chartered in 2016 as a project of OpenStreetMap US (OSM US) to provide operational support and strategic guidance for the educational outreach mission of OSM US. 

The TeachOSM website is an online resource to assist educators at all levels to introduce open source mapping using the OpenStreetMap ecosystem of tools in the classroom. Individual instructors are encouraged to make use of the instructional materials provided here to develop assignments for their particular discipline and curricular needs. This site provides the resources help instructors identify, assign, manage and grade a mapping assignment. This site also includes training documentation for both the instructor and students.

TeachOSM is led by a volunteer steering committee based throughout the United States, and relies upon teachers, students, and OpenStreetMappers all over the globe.

**3 themes**
1. Educational Content
2. Educator Training
3. Open Mapping Resources

**Comment by mcawley** [comment]
This is great Shawn!
