### ISSUE TITLE
[Landing Page] - Partner sites

### ISSUE THREAD

**Issue by sdpeyton** [GeoSurge/teachosm#5]
## Description
Add a section for displaying partnerships. In order to build out acceptance criteria, we need to know which partners we are going to display and how we want to display those relationships.

## Acceptance Criteria
[Need more info to build out acceptance criteria]

## Mocks

![image](https://user-images.githubusercontent.com/11160004/54167953-bc592580-4442-11e9-850c-dd179a078e8c.png)

![image](https://user-images.githubusercontent.com/11160004/54167970-c549f700-4442-11e9-8cee-eb26b90b4435.png)

**Comment by mcawley** [comment]
OpenStreetMap US - partner? AAG?

**Comment by mcawley** [comment]
Call it something like 'our community' instead? moral supporters? :) AAG, AGS, OSMUS...

**Comment by geomantic** [comment]
It's good to have a section for our Partners, but I suppose TeachOSM will have to determine what it means to be a partner.

**Comment by shawnmgoulet** [comment]
@geomantic & @mcawley will need to supply a list of partners.

**Comment by mcawley** [comment]
We don't really have any yet. Not officially at least.

**Comment by shawnmgoulet** [comment]
If there aren't any, this section should be dropped.

**Comment by d3netxer** [comment]
sounds good, closing issue
