### ISSUE TITLE
[Landing Page] - Contact us

### ISSUE THREAD

**Issue by sdpeyton** [GeoSurge/teachosm#6]
## Description
We need a "contact us" section that allows the user to submit their email information and send an email to TeachOSM. 

## Acceptance Criteria
- [x] Create inputs for `name`, `email`, and `message`
- [ ] Hook up the submit button to send an email to [insert email to send to here]
- [ ] Update the background image to [insert background image preference here]

## Mocks
![image](https://user-images.githubusercontent.com/11160004/54168073-38ec0400-4443-11e9-8555-9819b311d4b8.png)

![image](https://user-images.githubusercontent.com/11160004/54168081-41443f00-4443-11e9-9877-1818da837585.png)

**Comment by d3netxer** [comment]
contact us form will send e-mail to: info@teachosm.org

**Comment by DanielJDufour** [comment]
I need to set up email forwarding

**Comment by sdpeyton** [comment]
done
