### ISSUE TITLE
[Front Page] new icons for Front page

### ISSUE THREAD

**Issue by d3netxer** [GeoSurge/teachosm#74]
## Description
The current icons were chosen from available ones in the Awesome Fonts set. In my opinion, they are ok at best. They look nice, but don't adequately represent the three subjects. Let's explore trying to get custom ones made. Please comment and submit ideas and comments for the proposed designs.

### current icons
<img width="1194" alt="Screen Shot 2019-07-15 at 10 39 39 AM" src="https://user-images.githubusercontent.com/2665840/61224595-dbb3d800-a6ec-11e9-9830-36f203227d50.png">

## Ideas for new icons

Educational content:

-Stack of books, and a globe

Educator Training:

-marked calendar (and a graduation cap?)

Open Mapping Resources:

-outstretched sharing hands, and a building/s, road/s, and marker in-between.

**Comment by shawnmgoulet** [comment]
@DanielJDufour IMO best starting icons would go something like:

**[Educational Content](https://fontawesome.com/icons/chalkboard-teacher?style=solid)** - but with a human looking at a globe

**[Educator Training](https://www.123rf.com/photo_14550710_office-icon.html)** - but with a person in front of people around a roundtable or 2

**[Open Mapping Resources](http://www.ckschools.org/UserFiles/Servers/Server_11091/Image/Teaching%20&%20Learning/Technology/digital_resources_icon.png)** - something like this could work

**Comment by d3netxer** [comment]
sounds good, anyone else have any ideas? I can start looking into getting drafts next week.

**Comment by mcawley** [comment]
Like the map theme of course! I tend towards simplicity with icons - books/globe/etc are good. I think the graduation cap is more US than anywhere else though so I usually shy away from that one.

**Comment by d3netxer** [comment]
@shawnmgoulet I like your ideas, but is there a way so alter one of the Educational Content or Open Mapping Resources icons so that they don't both have a globe?

**Comment by shawnmgoulet** [comment]
@d3netxer do you mean, do I have the means to make an icon? 

I don't have a paid noun project or some other icon library/customize/generator service subscription - my suggestions above were just examples of what I thought could work.

Does TOSM to generate these icons or is that something that GS can do?

**Comment by d3netxer** [comment]
completed
