### ISSUE TITLE
Put add project button on right hand side of search bar on projects page

### ISSUE THREAD

**Issue by sdpeyton** [GeoSurge/teachosm#79]
Leave as FAB on mobile

**Comment by sdpeyton** [comment]
@d3netxer did teachosm confirm that this is the desired behavior?

**Comment by d3netxer** [comment]
we did not discuss

**Comment by d3netxer** [comment]
we discussed tonight and agreed to move the project button to the top middle of the page or next to the filer button. In addition the we discussed:
- explore possibly using columns for the different field in the project boxes

**Comment by d3netxer** [comment]
complete
